services:
  laravelmail.com:
    build:
      context: .
    container_name: laravelmail.com
    image: izdrail/laravelmail.com:latest
    restart: always
    ports:
      - "1100:1100"   # Backend service port
      - "1101:1101"   # Backend service port
    volumes:
      - ./backend:/home/backend
      - ./frontend:/home/frontend